In [2]:
import pandas as pd
import requests

In [3]:
df = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")

In [4]:
df[0]

,Postcode,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Harbourfront
5,M5A,Downtown Toronto,Regent Park
6,M6A,North York,Lawrence Heights
7,M6A,North York,Lawrence Manor
8,M7A,Queen's Park,Not assigned
9,M8A,Not assigned,Not assigned
10,M9A,Etobicoke,Islington Avenue
11,M1B,Scarborough,Rouge
12,M1B,Scarborough,Malvern
13,M2B,Not assigned,Not assigned
14,M3B,North York,Don Mills North
15,M4B,East York,Woodbine Gardens
16,M4B,East York,Parkview Hill
17,M5B,Downtown Toronto,Ryerson
18,M5B,Downtown Toronto,Garden District
19,M6B,North York,Glencairn
20,M7B,Not assigned,Not assigned
21,M8B,Not assigned,Not assigned
22,M9B,Etobicoke,Cloverdale
23,M9B,Etobicoke,Islington
24,M9B,Etobicoke,Martin Grove
25,M9B,Etobicoke,Princess Gardens
26,M9B,Etobicoke,West Deane Park
27,M1C,Scarborough,Highland Creek
28,M1C,Scarborough,Rouge Hill
29,M1C,Scarborough,Port Union
...,...,...,...
258,M9X,Not assigned,Not assigned
259,M1Y,Not assigned,Not assigned
260,M2Y,Not assigned,Not assigned
261,M3Y,Not assigned,Not assigned
262,M4Y,Downtown Toronto,Church and Wellesley
263,M5Y,Not assigned,Not assigned
264,M6Y,Not assigned,Not assigned
265,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
266,M8Y,Etobicoke,Humber Bay
267,M8Y,Etobicoke,King's Mill Park
268,M8Y,Etobicoke,Kingsway Park South East
269,M8Y,Etobicoke,Mimico NE
270,M8Y,Etobicoke,Old Mill South
271,M8Y,Etobicoke,The Queensway East
272,M8Y,Etobicoke,Royal York South East
273,M8Y,Etobicoke,Sunnylea
274,M9Y,Not assigned,Not assigned
275,M1Z,Not assigned,Not assigned
276,M2Z,Not assigned,Not assigned
277,M3Z,Not assigned,Not assigned
278,M4Z,Not assigned,Not assigned
279,M5Z,Not assigned,Not assigned
280,M6Z,Not assigned,Not assigned
281,M7Z,Not assigned,Not assigned
282,M8Z,Etobicoke,Kingsway Park South West
283,M8Z,Etobicoke,Mimico NW
284,M8Z,Etobicoke,The Queensway West
285,M8Z,Etobicoke,Royal York South West
286,M8Z,Etobicoke,South of Bloor
287,M9Z,Not assigned,Not assigned

In [5]:
df_postalcodes = df[0]

In [6]:
df_postalcodes.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [7]:
df_postalcodes["Borough"].value_counts()

Not assigned        77
Etobicoke           45
North York          38
Downtown Toronto    37
Scarborough         37
Central Toronto     17
West Toronto        13
York                 9
East Toronto         7
East York            6
Mississauga          1
Queen's Park         1
Name: Borough, dtype: int64

In [8]:
cond_borough = (df_postalcodes["Borough"] != "Not assigned")

In [9]:
df_postalcodes = df_postalcodes[cond_borough]

In [10]:
df_postalcodes.shape

(211, 3)

In [11]:
df_postalcodes.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [12]:
df_postalcodes.reset_index(drop = True, inplace = True)

In [13]:
df_postalcodes.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Not assigned
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

In [14]:
cond_nbhd = df_postalcodes["Neighbourhood"] == "Not assigned"

In [15]:
cond_nbhd.value_counts()

False    210
True       1
Name: Neighbourhood, dtype: int64

In [16]:
df_postalcodes.iloc[6, 2] = df_postalcodes.iloc[6, 1]

/Users/ahmadzainichia/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/ahmadzainichia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [17]:
df_postalcodes.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Queen's Park
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

In [18]:
postal_codes = df_postalcodes["Postcode"].value_counts().to_frame()

In [19]:
postal_codes.shape

(103, 1)

In [20]:
postal_codes.head()

     Postcode
M8Y         8
M9V         8
M5V         7
M8Z         5
M4V         5

In [21]:
df_postalcodes_grouped = df_postalcodes.groupby(["Postcode", "Borough"])["Neighbourhood"].apply(', '.join)

In [22]:
df_postalcodes_grouped = df_postalcodes_grouped.to_frame()

In [23]:
df_postalcodes_grouped.reset_index(inplace = True)

In [24]:
df_postalcodes_grouped.head(10)

  Postcode      Borough                                    Neighbourhood
0      M1B  Scarborough                                   Rouge, Malvern
1      M1C  Scarborough           Highland Creek, Rouge Hill, Port Union
2      M1E  Scarborough                Guildwood, Morningside, West Hill
3      M1G  Scarborough                                           Woburn
4      M1H  Scarborough                                        Cedarbrae
5      M1J  Scarborough                              Scarborough Village
6      M1K  Scarborough      East Birchmount Park, Ionview, Kennedy Park
7      M1L  Scarborough                  Clairlea, Golden Mile, Oakridge
8      M1M  Scarborough  Cliffcrest, Cliffside, Scarborough Village West
9      M1N  Scarborough                      Birch Cliff, Cliffside West

In [25]:
df_postalcodes_grouped.shape

(103, 3)

In [26]:
df_postalcodes_grouped.sort_values(by = "Postcode")

,Postcode,Borough,Neighbourhood
0,M1B,Scarborough,"Rouge, Malvern"
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park"
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge"
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff, Cliffside West"
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ..."
11,M1R,Scarborough,"Maryvale, Wexford"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter"
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St..."
15,M1W,Scarborough,L'Amoreaux West
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview, Henry Farm, Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"Silver Hills, York Mills"
21,M2M,North York,"Newtonbrook, Willowdale"
22,M2N,North York,Willowdale South
23,M2P,North York,York Mills West
24,M2R,North York,Willowdale West
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills North
27,M3C,North York,"Flemingdon Park, Don Mills South"
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights"
29,M3J,North York,"Northwood Park, York University"
...,...,...,...
73,M6C,York,Humewood-Cedarvale
74,M6E,York,Caledonia-Fairbanks
75,M6G,Downtown Toronto,Christie
76,M6H,West Toronto,"Dovercourt Village, Dufferin"
77,M6J,West Toronto,"Little Portugal, Trinity"
78,M6K,West Toronto,"Brockton, Exhibition Place, Parkdale Village"
79,M6L,North York,"Downsview, North Park, Upwood Park"
80,M6M,York,"Del Ray, Keelesdale, Mount Dennis, Silverthorn"
81,M6N,York,"The Junction North, Runnymede"
82,M6P,West Toronto,"High Park, The Junction South"
83,M6R,West Toronto,"Parkdale, Roncesvalles"
84,M6S,West Toronto,"Runnymede, Swansea"
85,M7A,Queen's Park,Queen's Park
86,M7R,Mississauga,Canada Post Gateway Processing Centre
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto"
89,M8W,Etobicoke,"Alderwood, Long Branch"
90,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
91,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So..."
92,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen..."
93,M9A,Etobicoke,Islington Avenue
94,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."
95,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol..."
96,M9L,North York,Humber Summit
97,M9M,North York,"Emery, Humberlea"
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv..."
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ..."
102,M9W,Etobicoke,Northwest

In [27]:
df_postalcodes_grouped.head()

  Postcode      Borough                           Neighbourhood
0      M1B  Scarborough                          Rouge, Malvern
1      M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2      M1E  Scarborough       Guildwood, Morningside, West Hill
3      M1G  Scarborough                                  Woburn
4      M1H  Scarborough                               Cedarbrae

In [28]:
df_postalcodes_grouped.shape

(103, 3)

In [29]:
df_LocationData = pd.read_csv("https://cocl.us/Geospatial_data")

In [30]:
df_LocationData.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [31]:
cond = df_LocationData["Postal Code"] == df_postalcodes_grouped["Postcode"]

In [32]:
cond.value_counts()

True    103
dtype: int64

In [33]:
df_postalcodes_final = pd.concat([df_postalcodes_grouped, df_LocationData], axis = 1, join = 'inner')

In [34]:
df_postalcodes_final.head()

,Postcode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",M1B,43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",M1C,43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",M1E,43.763573,-79.188711
3,M1G,Scarborough,Woburn,M1G,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,M1H,43.773136,-79.239476

In [35]:
df_postalcodes_final.drop(["Postal Code"], axis = 1, inplace = True)

In [36]:
df_postalcodes_final.head()

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476